name: MarcosArizmendi
favicon: null
layout_spectrum: 0.50049
typography_spectrum: 0.27722
title: Marcos Arizmendi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000132'
    - '#0139ad'
    - '#692d00'
    - '#bf5f00'
    - '#dfb58c'
  brandStrength: 0.5
  lightness: 0.5692982859909534
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
