name: MarcosArizmendi
favicon: null
layout_spectrum: 0.75906
typography_spectrum: 0.27722
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000132'
    - '#0139ad'
    - '#692d00'
    - '#bf5f00'
    - '#dfb58c'
  brandStrength: 0.5
  lightness: 0.5692982859909534
  saturation: 0.30342674092389643
  rhythmicContrast: 0.8376270546577871
purpose: []
